# Generated by Django 5.0 on 2023-12-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Link Rubber Fairylights', 'Link Rubber Fairylights'), ('No-Link Rubber Fairylights', 'No-Link Rubber Fairylights'), ('Link Pvc Fairylights', 'Link Pvc Fairylights'), ('No-Link Pvc Fairylights', 'No-Link Pvc Fairylights'), ('Round Ropelights', 'Round Ropelights'), ('Flat Ropelights', 'Flat Ropelights')], max_length=100, null=True)),
                ('color', models.CharField(blank=True, choices=[('Red Stdy', 'Red Stdy'), ('Red Twkl', 'Red Twkl'), ('Red', 'Red'), ('Blue Stdy', 'Blue Stdy'), ('Blue Twkl', 'Blue Twkl'), ('Blue', 'Blue'), ('Green Stdy', 'Green Stdy'), ('Green Twkl', 'Green Twkl'), ('Green', 'Green'), ('C.White Stdy', 'C.White Stdy'), ('C.White Twkl', 'C.White Twkl'), ('C.White', 'C.White'), ('W.White Stdy', 'W.White Stdy'), ('W.White Twkl', 'W.White Twkl'), ('W.White', 'W.White'), ('M.Color Stdy', 'M.Color Stdy'), ('M.Color Twkl', 'M.Color Twkl'), ('M.Color', 'M.Color'), ('Pink Stdy', 'Pink Stdy'), ('Pink Twkl', 'Pink Twkl'), ('Pink', 'Pink'), ('Purple Stdy', 'Purple Stdy'), ('Purple Twkl', 'Purple Twkl'), ('Purple', 'Purple'), ('Orange Stdy', 'Orange Stdy'), ('Orange Twkl', 'Orange Twkl'), ('Orange', 'Orange')], max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Meter(s)', 'Meter(s)'), ('Unit(s)', 'Unit(s)'), ('Packet(s)', 'Packet(s)'), ('Roll(s)', 'Roll(s)')], max_length=100, null=True)),
                ('stock_code', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('shelf_id', models.CharField(blank=True, max_length=100, null=True)),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
