# Generated by Django 5.0 on 2023-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Link Rubber Fairylights', 'Link Rubber Fairylights'), ('No-Link Rubber Fairylights', 'No-Link Rubber Fairylights'), ('Link Pvc Fairylights', 'Link Pvc Fairylights'), ('No-Link Pvc Fairylights', 'No-Link Pvc Fairylights'), ('Round Ropelights', 'Round Ropelights'), ('Flat Ropelights', 'Flat Ropelights'), ('Cable Ties', 'Cable Ties'), ('Control Blocks', 'Control Blocks'), ('Enclosure', 'Enclosure'), ('Tee Joint', 'Tee Joint'), ('Straight Joint', 'Straight Joint')], max_length=100, null=True),
        ),
    ]
