# Generated by Django 5.0 on 2023-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stock_size_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Link Rubber', 'Link Rubber'), ('No-Link Rubber', 'No-Link Rubber'), ('Link Pvc', 'Link Pvc'), ('No-Link Pvc', 'No-Link Pvc'), ('Round Rope', 'Round Rope'), ('Flat Rope', 'Flat Rope'), ('Cable Ties', 'Cable Ties'), ('Control Blocks', 'Control Blocks'), ('Enclosure', 'Enclosure'), ('Tee Joint', 'Tee Joint'), ('Straight Joint', 'Straight Joint')], max_length=100, null=True),
        ),
    ]
