# Generated by Django 5.0 on 2023-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
