# Generated by Django 5.0 on 2023-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_stock_receive_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Fairylts Rub-L', 'Fairylts Rub-L'), ('Fairylts Rub-NL', 'Fairylts Rub-NL'), ('Fairylts Pvc-L', 'Fairylts Pvc-L'), ('Fairylts Pvc-NL', 'Fairylts Pvc-NL'), ('Round Rope', 'Round Rope'), ('Flat Rope', 'Flat Rope'), ('Cable Ties', 'Cable Ties'), ('Control Blocks', 'Control Blocks'), ('Enclosure', 'Enclosure'), ('Tee Joint', 'Tee Joint'), ('Straight Joint', 'Straight Joint')], max_length=100, null=True),
        ),
    ]
