# Generated by Django 5.0 on 2023-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_stock_category_alter_stock_container_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Fairylts Rub-L', 'Fairylts Rub-L'), ('Fairylts Rub-NL', 'Fairylts Rub-NL'), ('Fairylts Pvc-L', 'Fairylts Pvc-L'), ('Fairylts Pvc-NL', 'Fairylts Pvc-NL'), ('Round Rope', 'Round Rope'), ('Flat Rope', 'Flat Rope'), ('Cable Ties', 'Cable Ties'), ('Control Block', 'Control Block'), ('Enclosure', 'Enclosure'), ('Tee Joint', 'Tee Joint'), ('Straight Joint', 'Straight Joint'), ('F16 v4', 'F16 v4'), ('F16 v3', 'F16 v3'), ('F4', ' F4'), ('F48', 'F48'), ('Power Supply', 'Power Supply')], max_length=100, null=True),
        ),
    ]
